name: awesome-Cloudflare-IPs
services:
  main:
    image: uhub.service.ucloud.cn/syshub/awesome-cloudflare-ips
    environment:
      - CLOUD_SDK_AK=
      - CLOUD_SDK_SK=
      - DOMAIN=
      - APP_ID=
      - INSTALLATION_ID=
      - REPO=
